name: CI_action

on:
  push:
    branches: [Master]
  pull_request:
    branches: [Master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ./Worksheet2/my-react-app

      - name: Run the tests
        run: npm test
        working-directory: ./Worksheet2/my-react-app

      - name: Build
        run: npm run build
        working-directory: ./Worksheet2/my-react-app
